language: rust
rust:
- nightly
install:
- ci/install.sh
cache:
- cargo
- pip
before_cache:
- chmod -R a+r $HOME/.cargo
script:
- cargo build
- cargo test
after_success: "./ci/deploy.sh"
env:
  global:
  - secure: Fmcmbrkl4oD65i0rquPzI/CMm8/Mxl+eQ1VLVEprIKb3WfDn6QUtwz8k+0KlUfhxajqvt8spxFbRUxS7msGvlOUKgKSVILTyY8c0UcIB4kxKwHWUSLMAgmYwGLnn7CAnQLzAjre5t747v0xoSbBwxFl0mP31mJgmtZuBbKfQv3SpTutTxsJj98UxOjR32TYi1UfMUK0YsCZQJHfc1U6tESTAs13h/8RTpdWra7blTTUlP8EwN+kClYW1eMpiAmW/4/xDVtlBIgXdJcL/SQSbakDC8S44+wEqlrRjsEGkihOGr2pN+pa3m8Fn1nV7IZSxHCXv7G8ysA0Rhsk5tdMYuPYVKFgQWni2HUmNi/f4X4uFBfpUrWqnykwh1c1VjFDvPDbTYwGwyZB3YPn94quLs80PdmxK4ZL6xb1wsp7s/hJKdjrtC3lroGRPBBLI+3YdUp/WQrBICZA4/YdpJVC8QTDMdzrtarBbM1fs1kIb8Cq0tMvLvawt4HqH3PS19F8GHU3d0vE93W1Hc9n2QLm+EWRCDApIJLJ72TFI6NyYwTvM8oFNrlzhs2Shg6LBomMRg95GPG7xISSkkgUrsJaH8r1njoDXZohe3kAsY31ZPoVFsiVAhL7FoNFctnxYqE8D99EJgP7Knv5eGLReP9hFuviLKTjl2C0Dpwq5osJtNcU=
